/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.voice;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Intent</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.voice.Intent#getIsFollowup <em>Is Followup</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.voice.Intent#getQuestion <em>Question</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.voice.Intent#getTraining <em>Training</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.voice.VoicePackage#getIntent()
 * @model
 * @generated
 */
public interface Intent extends Agent
{
  /**
   * Returns the value of the '<em><b>Is Followup</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Is Followup</em>' containment reference.
   * @see #setIsFollowup(IsFollowup)
   * @see org.xtext.example.mydsl.voice.VoicePackage#getIntent_IsFollowup()
   * @model containment="true"
   * @generated
   */
  IsFollowup getIsFollowup();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.voice.Intent#getIsFollowup <em>Is Followup</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Is Followup</em>' containment reference.
   * @see #getIsFollowup()
   * @generated
   */
  void setIsFollowup(IsFollowup value);

  /**
   * Returns the value of the '<em><b>Question</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.voice.Question}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Question</em>' containment reference list.
   * @see org.xtext.example.mydsl.voice.VoicePackage#getIntent_Question()
   * @model containment="true"
   * @generated
   */
  EList<Question> getQuestion();

  /**
   * Returns the value of the '<em><b>Training</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Training</em>' containment reference.
   * @see #setTraining(Training)
   * @see org.xtext.example.mydsl.voice.VoicePackage#getIntent_Training()
   * @model containment="true"
   * @generated
   */
  Training getTraining();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.voice.Intent#getTraining <em>Training</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Training</em>' containment reference.
   * @see #getTraining()
   * @generated
   */
  void setTraining(Training value);

} // Intent
