/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.voice;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Is Followup</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.voice.IsFollowup#getIntent <em>Intent</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.voice.VoicePackage#getIsFollowup()
 * @model
 * @generated
 */
public interface IsFollowup extends EObject
{
  /**
   * Returns the value of the '<em><b>Intent</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Intent</em>' reference.
   * @see #setIntent(Intent)
   * @see org.xtext.example.mydsl.voice.VoicePackage#getIsFollowup_Intent()
   * @model
   * @generated
   */
  Intent getIntent();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.voice.IsFollowup#getIntent <em>Intent</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Intent</em>' reference.
   * @see #getIntent()
   * @generated
   */
  void setIntent(Intent value);

} // IsFollowup
