/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.voice;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Question Reference</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.voice.QuestionReference#getQuestion <em>Question</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.voice.QuestionReference#getQuestionReference <em>Question Reference</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.voice.VoicePackage#getQuestionReference()
 * @model
 * @generated
 */
public interface QuestionReference extends EObject
{
  /**
   * Returns the value of the '<em><b>Question</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Question</em>' containment reference.
   * @see #setQuestion(Question)
   * @see org.xtext.example.mydsl.voice.VoicePackage#getQuestionReference_Question()
   * @model containment="true"
   * @generated
   */
  Question getQuestion();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.voice.QuestionReference#getQuestion <em>Question</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Question</em>' containment reference.
   * @see #getQuestion()
   * @generated
   */
  void setQuestion(Question value);

  /**
   * Returns the value of the '<em><b>Question Reference</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Question Reference</em>' reference.
   * @see #setQuestionReference(Question)
   * @see org.xtext.example.mydsl.voice.VoicePackage#getQuestionReference_QuestionReference()
   * @model
   * @generated
   */
  Question getQuestionReference();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.voice.QuestionReference#getQuestionReference <em>Question Reference</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Question Reference</em>' reference.
   * @see #getQuestionReference()
   * @generated
   */
  void setQuestionReference(Question value);

} // QuestionReference
