/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.voice;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Reference Object</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.voice.VoicePackage#getReferenceObject()
 * @model
 * @generated
 */
public interface ReferenceObject extends Agent
{
} // ReferenceObject
