/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.voice;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sysvariable</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.voice.Sysvariable#getDefaultValue <em>Default Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.voice.VoicePackage#getSysvariable()
 * @model
 * @generated
 */
public interface Sysvariable extends ReferenceObject
{
  /**
   * Returns the value of the '<em><b>Default Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Default Value</em>' attribute.
   * @see #setDefaultValue(String)
   * @see org.xtext.example.mydsl.voice.VoicePackage#getSysvariable_DefaultValue()
   * @model
   * @generated
   */
  String getDefaultValue();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.voice.Sysvariable#getDefaultValue <em>Default Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Default Value</em>' attribute.
   * @see #getDefaultValue()
   * @generated
   */
  void setDefaultValue(String value);

} // Sysvariable
