/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.voice;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Training Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.voice.VoicePackage#getTrainingRef()
 * @model
 * @generated
 */
public interface TrainingRef extends EObject
{
} // TrainingRef
