/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.voice;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.voice.VoiceFactory
 * @model kind="package"
 * @generated
 */
public interface VoicePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "voice";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/Voice";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "voice";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  VoicePackage eINSTANCE = org.xtext.example.mydsl.voice.impl.VoicePackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.voice.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.voice.impl.ModelImpl
   * @see org.xtext.example.mydsl.voice.impl.VoicePackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Agent</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__AGENT = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.voice.impl.AgentImpl <em>Agent</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.voice.impl.AgentImpl
   * @see org.xtext.example.mydsl.voice.impl.VoicePackageImpl#getAgent()
   * @generated
   */
  int AGENT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Agent</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AGENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.voice.impl.IntentImpl <em>Intent</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.voice.impl.IntentImpl
   * @see org.xtext.example.mydsl.voice.impl.VoicePackageImpl#getIntent()
   * @generated
   */
  int INTENT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTENT__NAME = AGENT__NAME;

  /**
   * The feature id for the '<em><b>Is Followup</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTENT__IS_FOLLOWUP = AGENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Question</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTENT__QUESTION = AGENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Training</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTENT__TRAINING = AGENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Intent</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTENT_FEATURE_COUNT = AGENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.voice.impl.EntityImpl <em>Entity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.voice.impl.EntityImpl
   * @see org.xtext.example.mydsl.voice.impl.VoicePackageImpl#getEntity()
   * @generated
   */
  int ENTITY = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__NAME = AGENT__NAME;

  /**
   * The feature id for the '<em><b>Example</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY__EXAMPLE = AGENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Entity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_FEATURE_COUNT = AGENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.voice.impl.QuestionImpl <em>Question</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.voice.impl.QuestionImpl
   * @see org.xtext.example.mydsl.voice.impl.VoicePackageImpl#getQuestion()
   * @generated
   */
  int QUESTION = 4;

  /**
   * The feature id for the '<em><b>Question Entity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION__QUESTION_ENTITY = 0;

  /**
   * The feature id for the '<em><b>Prompt</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION__PROMPT = 1;

  /**
   * The number of structural features of the '<em>Question</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.voice.impl.QuestionEntityImpl <em>Question Entity</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.voice.impl.QuestionEntityImpl
   * @see org.xtext.example.mydsl.voice.impl.VoicePackageImpl#getQuestionEntity()
   * @generated
   */
  int QUESTION_ENTITY = 5;

  /**
   * The feature id for the '<em><b>With Entity</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION_ENTITY__WITH_ENTITY = 0;

  /**
   * The number of structural features of the '<em>Question Entity</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUESTION_ENTITY_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.voice.impl.TrainingImpl <em>Training</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.voice.impl.TrainingImpl
   * @see org.xtext.example.mydsl.voice.impl.VoicePackageImpl#getTraining()
   * @generated
   */
  int TRAINING = 6;

  /**
   * The feature id for the '<em><b>Trainingref</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRAINING__TRAININGREF = 0;

  /**
   * The number of structural features of the '<em>Training</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRAINING_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.voice.impl.TrainingRefImpl <em>Training Ref</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.voice.impl.TrainingRefImpl
   * @see org.xtext.example.mydsl.voice.impl.VoicePackageImpl#getTrainingRef()
   * @generated
   */
  int TRAINING_REF = 7;

  /**
   * The number of structural features of the '<em>Training Ref</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRAINING_REF_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.voice.impl.DeclarationImpl <em>Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.voice.impl.DeclarationImpl
   * @see org.xtext.example.mydsl.voice.impl.VoicePackageImpl#getDeclaration()
   * @generated
   */
  int DECLARATION = 8;

  /**
   * The feature id for the '<em><b>Trainingstring</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION__TRAININGSTRING = 0;

  /**
   * The feature id for the '<em><b>Reference</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION__REFERENCE = 1;

  /**
   * The number of structural features of the '<em>Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.voice.impl.EntityExampleImpl <em>Entity Example</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.voice.impl.EntityExampleImpl
   * @see org.xtext.example.mydsl.voice.impl.VoicePackageImpl#getEntityExample()
   * @generated
   */
  int ENTITY_EXAMPLE = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_EXAMPLE__NAME = 0;

  /**
   * The number of structural features of the '<em>Entity Example</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ENTITY_EXAMPLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.voice.impl.IsFollowupImpl <em>Is Followup</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.voice.impl.IsFollowupImpl
   * @see org.xtext.example.mydsl.voice.impl.VoicePackageImpl#getIsFollowup()
   * @generated
   */
  int IS_FOLLOWUP = 10;

  /**
   * The feature id for the '<em><b>Intent</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IS_FOLLOWUP__INTENT = 0;

  /**
   * The number of structural features of the '<em>Is Followup</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IS_FOLLOWUP_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.voice.impl.SysvariableImpl <em>Sysvariable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.voice.impl.SysvariableImpl
   * @see org.xtext.example.mydsl.voice.impl.VoicePackageImpl#getSysvariable()
   * @generated
   */
  int SYSVARIABLE = 11;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSVARIABLE__VALUE = 0;

  /**
   * The number of structural features of the '<em>Sysvariable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSVARIABLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.voice.impl.ReferenceImpl <em>Reference</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.voice.impl.ReferenceImpl
   * @see org.xtext.example.mydsl.voice.impl.VoicePackageImpl#getReference()
   * @generated
   */
  int REFERENCE = 12;

  /**
   * The feature id for the '<em><b>Entity</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE__ENTITY = 0;

  /**
   * The feature id for the '<em><b>Sysvar</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE__SYSVAR = 1;

  /**
   * The number of structural features of the '<em>Reference</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REFERENCE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.voice.impl.TrainingRefSimpleImpl <em>Training Ref Simple</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.voice.impl.TrainingRefSimpleImpl
   * @see org.xtext.example.mydsl.voice.impl.VoicePackageImpl#getTrainingRefSimple()
   * @generated
   */
  int TRAINING_REF_SIMPLE = 13;

  /**
   * The feature id for the '<em><b>Declarations</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRAINING_REF_SIMPLE__DECLARATIONS = TRAINING_REF_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Training Ref Simple</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRAINING_REF_SIMPLE_FEATURE_COUNT = TRAINING_REF_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.voice.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.mydsl.voice.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.voice.Model#getAgent <em>Agent</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Agent</em>'.
   * @see org.xtext.example.mydsl.voice.Model#getAgent()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Agent();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.voice.Agent <em>Agent</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Agent</em>'.
   * @see org.xtext.example.mydsl.voice.Agent
   * @generated
   */
  EClass getAgent();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.voice.Agent#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.voice.Agent#getName()
   * @see #getAgent()
   * @generated
   */
  EAttribute getAgent_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.voice.Intent <em>Intent</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Intent</em>'.
   * @see org.xtext.example.mydsl.voice.Intent
   * @generated
   */
  EClass getIntent();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.voice.Intent#getIsFollowup <em>Is Followup</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Is Followup</em>'.
   * @see org.xtext.example.mydsl.voice.Intent#getIsFollowup()
   * @see #getIntent()
   * @generated
   */
  EReference getIntent_IsFollowup();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.voice.Intent#getQuestion <em>Question</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Question</em>'.
   * @see org.xtext.example.mydsl.voice.Intent#getQuestion()
   * @see #getIntent()
   * @generated
   */
  EReference getIntent_Question();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.voice.Intent#getTraining <em>Training</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Training</em>'.
   * @see org.xtext.example.mydsl.voice.Intent#getTraining()
   * @see #getIntent()
   * @generated
   */
  EReference getIntent_Training();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.voice.Entity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entity</em>'.
   * @see org.xtext.example.mydsl.voice.Entity
   * @generated
   */
  EClass getEntity();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.voice.Entity#getExample <em>Example</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Example</em>'.
   * @see org.xtext.example.mydsl.voice.Entity#getExample()
   * @see #getEntity()
   * @generated
   */
  EReference getEntity_Example();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.voice.Question <em>Question</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Question</em>'.
   * @see org.xtext.example.mydsl.voice.Question
   * @generated
   */
  EClass getQuestion();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.voice.Question#getQuestionEntity <em>Question Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Question Entity</em>'.
   * @see org.xtext.example.mydsl.voice.Question#getQuestionEntity()
   * @see #getQuestion()
   * @generated
   */
  EReference getQuestion_QuestionEntity();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.voice.Question#getPrompt <em>Prompt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Prompt</em>'.
   * @see org.xtext.example.mydsl.voice.Question#getPrompt()
   * @see #getQuestion()
   * @generated
   */
  EAttribute getQuestion_Prompt();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.voice.QuestionEntity <em>Question Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Question Entity</em>'.
   * @see org.xtext.example.mydsl.voice.QuestionEntity
   * @generated
   */
  EClass getQuestionEntity();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.voice.QuestionEntity#getWithEntity <em>With Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>With Entity</em>'.
   * @see org.xtext.example.mydsl.voice.QuestionEntity#getWithEntity()
   * @see #getQuestionEntity()
   * @generated
   */
  EReference getQuestionEntity_WithEntity();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.voice.Training <em>Training</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Training</em>'.
   * @see org.xtext.example.mydsl.voice.Training
   * @generated
   */
  EClass getTraining();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.voice.Training#getTrainingref <em>Trainingref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Trainingref</em>'.
   * @see org.xtext.example.mydsl.voice.Training#getTrainingref()
   * @see #getTraining()
   * @generated
   */
  EReference getTraining_Trainingref();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.voice.TrainingRef <em>Training Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Training Ref</em>'.
   * @see org.xtext.example.mydsl.voice.TrainingRef
   * @generated
   */
  EClass getTrainingRef();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.voice.Declaration <em>Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Declaration</em>'.
   * @see org.xtext.example.mydsl.voice.Declaration
   * @generated
   */
  EClass getDeclaration();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.voice.Declaration#getTrainingstring <em>Trainingstring</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Trainingstring</em>'.
   * @see org.xtext.example.mydsl.voice.Declaration#getTrainingstring()
   * @see #getDeclaration()
   * @generated
   */
  EAttribute getDeclaration_Trainingstring();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.voice.Declaration#getReference <em>Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Reference</em>'.
   * @see org.xtext.example.mydsl.voice.Declaration#getReference()
   * @see #getDeclaration()
   * @generated
   */
  EReference getDeclaration_Reference();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.voice.EntityExample <em>Entity Example</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Entity Example</em>'.
   * @see org.xtext.example.mydsl.voice.EntityExample
   * @generated
   */
  EClass getEntityExample();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.voice.EntityExample#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.voice.EntityExample#getName()
   * @see #getEntityExample()
   * @generated
   */
  EAttribute getEntityExample_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.voice.IsFollowup <em>Is Followup</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Is Followup</em>'.
   * @see org.xtext.example.mydsl.voice.IsFollowup
   * @generated
   */
  EClass getIsFollowup();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.voice.IsFollowup#getIntent <em>Intent</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Intent</em>'.
   * @see org.xtext.example.mydsl.voice.IsFollowup#getIntent()
   * @see #getIsFollowup()
   * @generated
   */
  EReference getIsFollowup_Intent();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.voice.Sysvariable <em>Sysvariable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sysvariable</em>'.
   * @see org.xtext.example.mydsl.voice.Sysvariable
   * @generated
   */
  EClass getSysvariable();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.voice.Sysvariable#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.mydsl.voice.Sysvariable#getValue()
   * @see #getSysvariable()
   * @generated
   */
  EAttribute getSysvariable_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.voice.Reference <em>Reference</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Reference</em>'.
   * @see org.xtext.example.mydsl.voice.Reference
   * @generated
   */
  EClass getReference();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.voice.Reference#getEntity <em>Entity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Entity</em>'.
   * @see org.xtext.example.mydsl.voice.Reference#getEntity()
   * @see #getReference()
   * @generated
   */
  EReference getReference_Entity();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.voice.Reference#getSysvar <em>Sysvar</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Sysvar</em>'.
   * @see org.xtext.example.mydsl.voice.Reference#getSysvar()
   * @see #getReference()
   * @generated
   */
  EReference getReference_Sysvar();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.voice.TrainingRefSimple <em>Training Ref Simple</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Training Ref Simple</em>'.
   * @see org.xtext.example.mydsl.voice.TrainingRefSimple
   * @generated
   */
  EClass getTrainingRefSimple();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.voice.TrainingRefSimple#getDeclarations <em>Declarations</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Declarations</em>'.
   * @see org.xtext.example.mydsl.voice.TrainingRefSimple#getDeclarations()
   * @see #getTrainingRefSimple()
   * @generated
   */
  EReference getTrainingRefSimple_Declarations();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  VoiceFactory getVoiceFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.voice.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.voice.impl.ModelImpl
     * @see org.xtext.example.mydsl.voice.impl.VoicePackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Agent</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__AGENT = eINSTANCE.getModel_Agent();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.voice.impl.AgentImpl <em>Agent</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.voice.impl.AgentImpl
     * @see org.xtext.example.mydsl.voice.impl.VoicePackageImpl#getAgent()
     * @generated
     */
    EClass AGENT = eINSTANCE.getAgent();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AGENT__NAME = eINSTANCE.getAgent_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.voice.impl.IntentImpl <em>Intent</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.voice.impl.IntentImpl
     * @see org.xtext.example.mydsl.voice.impl.VoicePackageImpl#getIntent()
     * @generated
     */
    EClass INTENT = eINSTANCE.getIntent();

    /**
     * The meta object literal for the '<em><b>Is Followup</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTENT__IS_FOLLOWUP = eINSTANCE.getIntent_IsFollowup();

    /**
     * The meta object literal for the '<em><b>Question</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTENT__QUESTION = eINSTANCE.getIntent_Question();

    /**
     * The meta object literal for the '<em><b>Training</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INTENT__TRAINING = eINSTANCE.getIntent_Training();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.voice.impl.EntityImpl <em>Entity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.voice.impl.EntityImpl
     * @see org.xtext.example.mydsl.voice.impl.VoicePackageImpl#getEntity()
     * @generated
     */
    EClass ENTITY = eINSTANCE.getEntity();

    /**
     * The meta object literal for the '<em><b>Example</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ENTITY__EXAMPLE = eINSTANCE.getEntity_Example();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.voice.impl.QuestionImpl <em>Question</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.voice.impl.QuestionImpl
     * @see org.xtext.example.mydsl.voice.impl.VoicePackageImpl#getQuestion()
     * @generated
     */
    EClass QUESTION = eINSTANCE.getQuestion();

    /**
     * The meta object literal for the '<em><b>Question Entity</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUESTION__QUESTION_ENTITY = eINSTANCE.getQuestion_QuestionEntity();

    /**
     * The meta object literal for the '<em><b>Prompt</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute QUESTION__PROMPT = eINSTANCE.getQuestion_Prompt();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.voice.impl.QuestionEntityImpl <em>Question Entity</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.voice.impl.QuestionEntityImpl
     * @see org.xtext.example.mydsl.voice.impl.VoicePackageImpl#getQuestionEntity()
     * @generated
     */
    EClass QUESTION_ENTITY = eINSTANCE.getQuestionEntity();

    /**
     * The meta object literal for the '<em><b>With Entity</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUESTION_ENTITY__WITH_ENTITY = eINSTANCE.getQuestionEntity_WithEntity();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.voice.impl.TrainingImpl <em>Training</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.voice.impl.TrainingImpl
     * @see org.xtext.example.mydsl.voice.impl.VoicePackageImpl#getTraining()
     * @generated
     */
    EClass TRAINING = eINSTANCE.getTraining();

    /**
     * The meta object literal for the '<em><b>Trainingref</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRAINING__TRAININGREF = eINSTANCE.getTraining_Trainingref();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.voice.impl.TrainingRefImpl <em>Training Ref</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.voice.impl.TrainingRefImpl
     * @see org.xtext.example.mydsl.voice.impl.VoicePackageImpl#getTrainingRef()
     * @generated
     */
    EClass TRAINING_REF = eINSTANCE.getTrainingRef();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.voice.impl.DeclarationImpl <em>Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.voice.impl.DeclarationImpl
     * @see org.xtext.example.mydsl.voice.impl.VoicePackageImpl#getDeclaration()
     * @generated
     */
    EClass DECLARATION = eINSTANCE.getDeclaration();

    /**
     * The meta object literal for the '<em><b>Trainingstring</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DECLARATION__TRAININGSTRING = eINSTANCE.getDeclaration_Trainingstring();

    /**
     * The meta object literal for the '<em><b>Reference</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DECLARATION__REFERENCE = eINSTANCE.getDeclaration_Reference();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.voice.impl.EntityExampleImpl <em>Entity Example</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.voice.impl.EntityExampleImpl
     * @see org.xtext.example.mydsl.voice.impl.VoicePackageImpl#getEntityExample()
     * @generated
     */
    EClass ENTITY_EXAMPLE = eINSTANCE.getEntityExample();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ENTITY_EXAMPLE__NAME = eINSTANCE.getEntityExample_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.voice.impl.IsFollowupImpl <em>Is Followup</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.voice.impl.IsFollowupImpl
     * @see org.xtext.example.mydsl.voice.impl.VoicePackageImpl#getIsFollowup()
     * @generated
     */
    EClass IS_FOLLOWUP = eINSTANCE.getIsFollowup();

    /**
     * The meta object literal for the '<em><b>Intent</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IS_FOLLOWUP__INTENT = eINSTANCE.getIsFollowup_Intent();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.voice.impl.SysvariableImpl <em>Sysvariable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.voice.impl.SysvariableImpl
     * @see org.xtext.example.mydsl.voice.impl.VoicePackageImpl#getSysvariable()
     * @generated
     */
    EClass SYSVARIABLE = eINSTANCE.getSysvariable();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SYSVARIABLE__VALUE = eINSTANCE.getSysvariable_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.voice.impl.ReferenceImpl <em>Reference</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.voice.impl.ReferenceImpl
     * @see org.xtext.example.mydsl.voice.impl.VoicePackageImpl#getReference()
     * @generated
     */
    EClass REFERENCE = eINSTANCE.getReference();

    /**
     * The meta object literal for the '<em><b>Entity</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REFERENCE__ENTITY = eINSTANCE.getReference_Entity();

    /**
     * The meta object literal for the '<em><b>Sysvar</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REFERENCE__SYSVAR = eINSTANCE.getReference_Sysvar();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.voice.impl.TrainingRefSimpleImpl <em>Training Ref Simple</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.voice.impl.TrainingRefSimpleImpl
     * @see org.xtext.example.mydsl.voice.impl.VoicePackageImpl#getTrainingRefSimple()
     * @generated
     */
    EClass TRAINING_REF_SIMPLE = eINSTANCE.getTrainingRefSimple();

    /**
     * The meta object literal for the '<em><b>Declarations</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRAINING_REF_SIMPLE__DECLARATIONS = eINSTANCE.getTrainingRefSimple_Declarations();

  }

} //VoicePackage
