/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.voice.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.voice.Intent;
import org.xtext.example.mydsl.voice.IsFollowup;
import org.xtext.example.mydsl.voice.Question;
import org.xtext.example.mydsl.voice.Training;
import org.xtext.example.mydsl.voice.VoicePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Intent</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.voice.impl.IntentImpl#getHasFollowup <em>Has Followup</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.voice.impl.IntentImpl#getIsFollowup <em>Is Followup</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.voice.impl.IntentImpl#getQuestion <em>Question</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.voice.impl.IntentImpl#getTraining <em>Training</em>}</li>
 * </ul>
 *
 * @generated
 */
public class IntentImpl extends AgentImpl implements Intent
{
  /**
   * The default value of the '{@link #getHasFollowup() <em>Has Followup</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHasFollowup()
   * @generated
   * @ordered
   */
  protected static final String HAS_FOLLOWUP_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getHasFollowup() <em>Has Followup</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getHasFollowup()
   * @generated
   * @ordered
   */
  protected String hasFollowup = HAS_FOLLOWUP_EDEFAULT;

  /**
   * The cached value of the '{@link #getIsFollowup() <em>Is Followup</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIsFollowup()
   * @generated
   * @ordered
   */
  protected IsFollowup isFollowup;

  /**
   * The cached value of the '{@link #getQuestion() <em>Question</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getQuestion()
   * @generated
   * @ordered
   */
  protected EList<Question> question;

  /**
   * The cached value of the '{@link #getTraining() <em>Training</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTraining()
   * @generated
   * @ordered
   */
  protected Training training;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected IntentImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return VoicePackage.Literals.INTENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getHasFollowup()
  {
    return hasFollowup;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setHasFollowup(String newHasFollowup)
  {
    String oldHasFollowup = hasFollowup;
    hasFollowup = newHasFollowup;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VoicePackage.INTENT__HAS_FOLLOWUP, oldHasFollowup, hasFollowup));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IsFollowup getIsFollowup()
  {
    return isFollowup;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetIsFollowup(IsFollowup newIsFollowup, NotificationChain msgs)
  {
    IsFollowup oldIsFollowup = isFollowup;
    isFollowup = newIsFollowup;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, VoicePackage.INTENT__IS_FOLLOWUP, oldIsFollowup, newIsFollowup);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIsFollowup(IsFollowup newIsFollowup)
  {
    if (newIsFollowup != isFollowup)
    {
      NotificationChain msgs = null;
      if (isFollowup != null)
        msgs = ((InternalEObject)isFollowup).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - VoicePackage.INTENT__IS_FOLLOWUP, null, msgs);
      if (newIsFollowup != null)
        msgs = ((InternalEObject)newIsFollowup).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - VoicePackage.INTENT__IS_FOLLOWUP, null, msgs);
      msgs = basicSetIsFollowup(newIsFollowup, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VoicePackage.INTENT__IS_FOLLOWUP, newIsFollowup, newIsFollowup));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Question> getQuestion()
  {
    if (question == null)
    {
      question = new EObjectContainmentEList<Question>(Question.class, this, VoicePackage.INTENT__QUESTION);
    }
    return question;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Training getTraining()
  {
    return training;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTraining(Training newTraining, NotificationChain msgs)
  {
    Training oldTraining = training;
    training = newTraining;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, VoicePackage.INTENT__TRAINING, oldTraining, newTraining);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTraining(Training newTraining)
  {
    if (newTraining != training)
    {
      NotificationChain msgs = null;
      if (training != null)
        msgs = ((InternalEObject)training).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - VoicePackage.INTENT__TRAINING, null, msgs);
      if (newTraining != null)
        msgs = ((InternalEObject)newTraining).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - VoicePackage.INTENT__TRAINING, null, msgs);
      msgs = basicSetTraining(newTraining, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VoicePackage.INTENT__TRAINING, newTraining, newTraining));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case VoicePackage.INTENT__IS_FOLLOWUP:
        return basicSetIsFollowup(null, msgs);
      case VoicePackage.INTENT__QUESTION:
        return ((InternalEList<?>)getQuestion()).basicRemove(otherEnd, msgs);
      case VoicePackage.INTENT__TRAINING:
        return basicSetTraining(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case VoicePackage.INTENT__HAS_FOLLOWUP:
        return getHasFollowup();
      case VoicePackage.INTENT__IS_FOLLOWUP:
        return getIsFollowup();
      case VoicePackage.INTENT__QUESTION:
        return getQuestion();
      case VoicePackage.INTENT__TRAINING:
        return getTraining();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case VoicePackage.INTENT__HAS_FOLLOWUP:
        setHasFollowup((String)newValue);
        return;
      case VoicePackage.INTENT__IS_FOLLOWUP:
        setIsFollowup((IsFollowup)newValue);
        return;
      case VoicePackage.INTENT__QUESTION:
        getQuestion().clear();
        getQuestion().addAll((Collection<? extends Question>)newValue);
        return;
      case VoicePackage.INTENT__TRAINING:
        setTraining((Training)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case VoicePackage.INTENT__HAS_FOLLOWUP:
        setHasFollowup(HAS_FOLLOWUP_EDEFAULT);
        return;
      case VoicePackage.INTENT__IS_FOLLOWUP:
        setIsFollowup((IsFollowup)null);
        return;
      case VoicePackage.INTENT__QUESTION:
        getQuestion().clear();
        return;
      case VoicePackage.INTENT__TRAINING:
        setTraining((Training)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case VoicePackage.INTENT__HAS_FOLLOWUP:
        return HAS_FOLLOWUP_EDEFAULT == null ? hasFollowup != null : !HAS_FOLLOWUP_EDEFAULT.equals(hasFollowup);
      case VoicePackage.INTENT__IS_FOLLOWUP:
        return isFollowup != null;
      case VoicePackage.INTENT__QUESTION:
        return question != null && !question.isEmpty();
      case VoicePackage.INTENT__TRAINING:
        return training != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (hasFollowup: ");
    result.append(hasFollowup);
    result.append(')');
    return result.toString();
  }

} //IntentImpl
