/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.voice.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.voice.ReferenceObject;
import org.xtext.example.mydsl.voice.VoicePackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Reference Object</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ReferenceObjectImpl extends AgentImpl implements ReferenceObject
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ReferenceObjectImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return VoicePackage.Literals.REFERENCE_OBJECT;
  }

} //ReferenceObjectImpl
