/**
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.voice.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.example.mydsl.voice.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class VoiceFactoryImpl extends EFactoryImpl implements VoiceFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static VoiceFactory init()
  {
    try
    {
      VoiceFactory theVoiceFactory = (VoiceFactory)EPackage.Registry.INSTANCE.getEFactory(VoicePackage.eNS_URI);
      if (theVoiceFactory != null)
      {
        return theVoiceFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new VoiceFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public VoiceFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case VoicePackage.MODEL: return createModel();
      case VoicePackage.AGENT: return createAgent();
      case VoicePackage.INTENT: return createIntent();
      case VoicePackage.REFERENCE_OBJECT: return createReferenceObject();
      case VoicePackage.QUESTION_REFERENCE: return createQuestionReference();
      case VoicePackage.QUESTION: return createQuestion();
      case VoicePackage.QUESTION_ENTITY: return createQuestionEntity();
      case VoicePackage.REFERENCE: return createReference();
      case VoicePackage.TRAINING: return createTraining();
      case VoicePackage.TRAINING_REF: return createTrainingRef();
      case VoicePackage.DECLARATION: return createDeclaration();
      case VoicePackage.ENTITY_EXAMPLE: return createEntityExample();
      case VoicePackage.IS_FOLLOWUP: return createIsFollowup();
      case VoicePackage.ENTITY: return createEntity();
      case VoicePackage.SYSVARIABLE: return createSysvariable();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Agent createAgent()
  {
    AgentImpl agent = new AgentImpl();
    return agent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Intent createIntent()
  {
    IntentImpl intent = new IntentImpl();
    return intent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ReferenceObject createReferenceObject()
  {
    ReferenceObjectImpl referenceObject = new ReferenceObjectImpl();
    return referenceObject;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public QuestionReference createQuestionReference()
  {
    QuestionReferenceImpl questionReference = new QuestionReferenceImpl();
    return questionReference;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Question createQuestion()
  {
    QuestionImpl question = new QuestionImpl();
    return question;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public QuestionEntity createQuestionEntity()
  {
    QuestionEntityImpl questionEntity = new QuestionEntityImpl();
    return questionEntity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Reference createReference()
  {
    ReferenceImpl reference = new ReferenceImpl();
    return reference;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Training createTraining()
  {
    TrainingImpl training = new TrainingImpl();
    return training;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TrainingRef createTrainingRef()
  {
    TrainingRefImpl trainingRef = new TrainingRefImpl();
    return trainingRef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Declaration createDeclaration()
  {
    DeclarationImpl declaration = new DeclarationImpl();
    return declaration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EntityExample createEntityExample()
  {
    EntityExampleImpl entityExample = new EntityExampleImpl();
    return entityExample;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IsFollowup createIsFollowup()
  {
    IsFollowupImpl isFollowup = new IsFollowupImpl();
    return isFollowup;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Entity createEntity()
  {
    EntityImpl entity = new EntityImpl();
    return entity;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Sysvariable createSysvariable()
  {
    SysvariableImpl sysvariable = new SysvariableImpl();
    return sysvariable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VoicePackage getVoicePackage()
  {
    return (VoicePackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static VoicePackage getPackage()
  {
    return VoicePackage.eINSTANCE;
  }

} //VoiceFactoryImpl
