/*
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.voice.ui.internal.VoiceActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class VoiceExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(VoiceActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		VoiceActivator activator = VoiceActivator.getInstance();
		return activator != null ? activator.getInjector(VoiceActivator.ORG_XTEXT_EXAMPLE_MYDSL_VOICE) : null;
	}

}
