/*
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.scoping;

import java.util.ArrayList;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.Scopes;
import org.xtext.example.mydsl.voice.Agent;
import org.xtext.example.mydsl.voice.Intent;
import org.xtext.example.mydsl.voice.Model;
import org.xtext.example.mydsl.voice.Question;
import org.xtext.example.mydsl.voice.QuestionReference;
import org.xtext.example.mydsl.voice.VoicePackage;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class VoiceScopeProvider extends AbstractVoiceScopeProvider {
    @Override
    public IScope getScope(EObject context, EReference reference) {
        if (context instanceof Intent
                && reference == VoicePackage.Literals.INTENT__ZUPER) {
            Model model = (Model) context.eContainer();
            ArrayList<Intent> candidates = new ArrayList<Intent>();
            for(Agent agent : model.getAgent()) {
            	if(agent instanceof Intent) {
            		if(((Intent) agent) != ((Intent)context) ) {
            			candidates.add(((Intent)agent));
            		}
            	}
            }

            return Scopes.scopeFor(candidates);
        }
        
       else if (context instanceof QuestionReference
                && reference == VoicePackage.Literals.QUESTION_REFERENCE__QUESTION_REFERENCE) {
        	Intent intent = (Intent) context.eContainer();
        	intent = intent.getZuper();
        	ArrayList<Question> candidates = new ArrayList<Question>();
        	if(intent!=null) {
        		for(QuestionReference question: intent.getQuestions()) {
        				candidates.add(question.getQuestion());
        		}
        	}
        	return Scopes.scopeFor(candidates);
        	}
        return super.getScope(context, reference);
    }
}
