/*
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.voice.ui.internal.VoiceActivator;

public class VoiceUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return VoiceActivator.getInstance().getInjector("org.xtext.example.mydsl.Voice");
	}

}
