/*
 * generated by Xtext 2.21.0
 */
package org.xtext.example.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl.parser.antlr.internal.InternalVoiceParser;
import org.xtext.example.mydsl.services.VoiceGrammarAccess;

public class VoiceParser extends AbstractAntlrParser {

	@Inject
	private VoiceGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalVoiceParser createParser(XtextTokenStream stream) {
		return new InternalVoiceParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public VoiceGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(VoiceGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
